### ISSUE TITLE
add more content on methodology

### ISSUE THREAD

**Issue by cathydeng** [datamade/million-dollar-blocks#14]
data: what does it include? why isn't it public?

analysis: list out all the steps, assumptions. perhaps we should publish the code we have, without the data?

**Comment by fgregg** [comment]
It has people's names and addresses. And we don't want to make that public
we should link to the anonymized version made by Smart Chaicato

let's make a new repo without the data but with the Makefiles and others.

**Comment by cathydeng** [comment]
done
